services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: cd backend && yarn install && yarn build
    startCommand: cd backend && rsync -a backend/public/ /data/backend/public/ && yarn start
    healthCheckPath: /_health
    disk:
      name: strapi-data
      mountPath: /data/backend
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 12.18.4
      - key: NODE_ENV
        value: production
      - key: DATABASE_FILENAME
        value: /data/backend/strapi.db
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
